default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  timeout: 5000
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development: &development
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: demo_docker_development

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: demo_docker_test
